name: CribeClan
version: '${project.version}'
main: de.cribemc.cribeclan.CribeClan
api-version: 1.18
authors: [ ChunkEater32 ]
description: A full functional clan-system for cribe network
depend:
  - Vault
softdepend:
  - PlotSquared
  - PlaceholderAPI
commands:
  gilde:
